name: Development Deploy

on:
    workflow_dispatch:
    push:
        branches:
            - dev

jobs:
    deploy-dev:
        uses: ./.github/workflows/deploy.yaml
        with:
            environment: 'dev'
            docker_compose_file: 'docker-compose.dev.yml'
        secrets: inherit
